rm_manual:
  robot_type: "engineer"
  chassis:
    topic: "/controllers/chassis_controller/command"
    accel_x:
      - [ 200.0, 5. ]
    accel_y:
      - [ 200.0,5. ]
    accel_z:
      - [ 200.0,14. ]
    safety_power: 400
    capacitor_threshold: 0.1
    charge_power: 0
    extra_power: 5000
    burst_power: 999
    buffer_threshold: 10
    power_gain: 0.85
    speed_change_scale: 0.3
  vel:
    topic: "/cmd_vel"
    max_linear_x:
      - [ 50.0,3. ]
      - [ 80.0,3. ]
      - [ 200.0,3. ]
    max_linear_y:
      - [ 50.0,3. ]
      - [ 80.0,3. ]
      - [ 200.0,3. ]
    max_angular_z:
      - [ 50.0,6. ]
      - [ 80.0,6. ]
      - [ 200.0,6. ]
    gyro_move_reduction: 1
    gyro_rotate_reduction: 1
  servo:
    topic: "/servo_server/delta_twist_cmds"
    max_linear_x: 0.4
    max_linear_y: 0.4
    max_linear_z: 0.4
    max_angular_x: 1.3
    max_angular_y: 1.3
    max_angular_z: 3
  gimbal:
    topic: "/controllers/gimbal_controller/command"
    max_yaw_vel: 2.5
    max_pitch_vel: 1
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.0
  drag:
    topic: "/controllers/drag_controller/command"
    on_pos: 0.
    off_pos: -2.45
  joint7:
    topic: "/controllers/joint7_controller/command"
    on_pos: 0.
    off_pos: 1.715
  reversal:
    topic: "/controllers/multi_dof_controller/command"
  auto_search:
    pitch: [ -0.1, 0.1]
    yaw: [ -0.10, 0.10 ]
    angle_range: 3.14
    gimbal_search_vel: 0.6
    chassis_search_vel: 0.05
    chassis_tolerance: 0.1
    x_start_value: 1.2

  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/arm_trajectory_controller
      - controllers/gpio_controller
      - controllers/gimbal_controller
      - controllers/drag_controller
      - controllers/multi_dof_controller
      - controllers/joint7_controller

    calibration_controllers:
      - controllers/joint1_calibration_controller
      - controllers/joint2_calibration_controller
      - controllers/joint3_calibration_controller
      - controllers/joint4_calibration_controller
      - controllers/joint5_calibration_controller
      - controllers/joint6_calibration_controller
      - controllers/yaw_calibration_controller
      - controllers/pitch_calibration_controller
      - controllers/drag_calibration_controller
      - controllers/joint7_calibration_controller

  calibration_gather:
    - start_controllers:
        - controllers/joint4_calibration_controller
        - controllers/joint1_calibration_controller
        - controllers/joint2_calibration_controller
        - controllers/joint3_calibration_controller
        - controllers/joint6_calibration_controller
        - controllers/joint7_calibration_controller
        - controllers/yaw_calibration_controller
        - controllers/pitch_calibration_controller
        - controllers/drag_calibration_controller
      stop_controllers:
        - controllers/arm_trajectory_controller
        - controllers/gimbal_controller
        - controllers/drag_controller
        - controllers/joint7_controller
      services_name:
        - /controllers/joint4_calibration_controller/is_calibrated
        - /controllers/joint1_calibration_controller/is_calibrated
        - /controllers/joint2_calibration_controller/is_calibrated
        - /controllers/joint3_calibration_controller/is_calibrated
        - /controllers/joint6_calibration_controller/is_calibrated
        - /controllers/joint7_calibration_controller/is_calibrated
        - /controllers/yaw_calibration_controller/is_calibrated
        - /controllers/pitch_calibration_controller/is_calibrated
        - /controllers/drag_calibration_controller/is_calibrated
    - start_controllers:
        - controllers/joint4_calibration_controller
        - controllers/joint1_calibration_controller
        - controllers/joint5_calibration_controller
      stop_controllers:
        - controllers/arm_trajectory_controller
      services_name:
        - /controllers/joint4_calibration_controller/is_calibrated
        - /controllers/joint1_calibration_controller/is_calibrated
        - /controllers/joint5_calibration_controller/is_calibrated
