rm_manual:
  robot_type: "hero"
  chassis:
    topic: "/controllers/chassis_controller/command"
    accel_x:
      - [ 50.0,99.0 ]
    accel_y:
      - [ 50.0,99.0 ]
    accel_z:
      - [ 50.0,99.0 ]
    safety_power: 60
    capacitor_threshold: 0.1
    charge_power: 20
    extra_power: 30
    burst_power: 300
  vel:
    topic: "/cmd_vel"
    power_limit_topic: "/controllers/chassis_controller/command"
    max_linear_x:
      - [ 50.0,2.14 ]
      - [ 80.0,3.5 ]
      - [ 300.0,4.0 ]
    max_linear_y:
      - [ 50.0,2.14 ]
      - [ 80.0,3.5 ]
      - [ 300.0,4.0 ]
    max_angular_z:
      - [ 50.0,4.0 ]
      - [ 80.0,6.0 ]
      - [ 300.0,12.0 ]
    gyro_move_reduction: 0.20
    gyro_rotate_reduction: 0.7
  gimbal:
    topic: "/controllers/gimbal_controller/command"
    max_yaw_vel: 10
    max_pitch_vel: 8.37
    track_timeout: 0.5
    eject_sensitivity: 0.38
    target_cost_function:
      k_pos: 1.0
      k_vel: 0.0
      k_hp: 0.0
      k_freq: 99.0
      timeout: 0.1
  shooter:
    topic: "/controllers/shooter_controller/command"
    gimbal_error_tolerance: 0.15
    target_acceleration_tolerance: 1.0
    accleration_moving_average_num: 10
    speed_10m_per_speed: 10.0
    speed_15m_per_speed: 14.0
    speed_16m_per_speed: 16.0
    speed_18m_per_speed: 18.0
    speed_30m_per_speed: 30.0
    heat_limit:
      low_shoot_frequency: 1
      high_shoot_frequency: 3
      burst_shoot_frequency: 6
      safe_shoot_frequency: 1
      heat_coeff: 3.0
      type: "ID1_42MM"
  detection_switch:
    fail_limit: 10
    service_name: "/Processor/status_switch"

  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/orientation_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
    calibration_controllers:
      - controllers/trigger_calibration_controller

  shooter_calibration:
    - start_controllers:
        - controllers/trigger_calibration_controller
      stop_controllers:
        - controllers/shooter_controller
      services_name:
        - /controllers/trigger_calibration_controller/is_calibrated

  ui:
    trigger_change:
      - name: "chassis"
        config: { start_position: [ 400, 850 ], size: 15, width: 2, title: "chassis: " }
      - name: "gimbal"
        config: { start_position: [ 400, 800 ], size: 15, width: 2, title: "gimbal:  " }
      - name: "shooter"
        config: { start_position: [ 400, 750 ], size: 15, width: 2, title: "shooter:" }
      - name: "target"
        config: {start_position: [ 400, 700 ], size: 15, width: 2, title: "target:" }
    time_change:
      - name: "capacitor"
        config: { start_position: [ 900, 100 ], size: 15, width: 2, delay: 0.5 }
    fixed:
      - name: "4.5m_str"
        config: { type: "string", size: 10, width: 1, color: "yellow",
                  start_position: [ 1000, 375 ], content: "4.5" }
      - name: "5.3m_str"
        config: { type: "string", size: 10, width: 1, color: "yellow",
                  start_position: [ 1000, 393 ], content: "5.3m" }
      - name: "5.3m_line"
        config: { type: "line", width: 2, color: "orange",
                  start_position: [ 949, 391 ], end_position: [ 971, 391 ] }
      - name: "mid"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 960, 302 ], end_position: [ 960, 540 ] }
    flash:
      - name: "spin"
        config: { start_position: [ 900, 750 ], size: 15, width: 2,
                  color: "yellow", content: "please spin!!", delay: 0.8 }
      - name: "armor0"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor1"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor2"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor3"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
