rm_referee:
  robot_type: engineer
  ui:
    trigger_change:
      - name: "step"
        config: { start_position: [ 850, 700 ], size: 15, width: 2, title: "step:" }
      - name: "reversal"
        config: { start_position: [ 50, 550 ], size: 15, width: 2, title: "reversal:" }
      - name: "stone"
        config: { start_position: [ 50, 600 ], size: 15, width: 2, title: "stone:" }
      - name: "drag"
        config: { start_position: [ 50, 650 ], size: 15, width: 2, title: "drag:" }
      - name: "gripper"
        config: { start_position: [ 50, 700 ], size: 15, width: 2, title: "gripper:" }
      - name: "exchange"
        config: { start_position: [ 50, 800 ], size: 15, width: 2, title: "exchange:" }
      - name: "planning"
        config: { start_position: [ 850, 650 ], size: 15, width: 2, title: "planning:" }
      - name: "servo_mode"
        config: { start_position: [ 50, 750 ], size: 15, width: 2, title: "mode:" }
    fixed:
      - name: "line1"
        config: { type: "line", width: 3, color: "orange",
                  start_position: [ 1900, 540 ], end_position: [ 0, 540 ] }
#      - name: "lf_sky1"
#        config: { type: "line", width: 2, color: "yellow",
#                  start_position: [ 872, 0 ], end_position: [ 874, 1080 ] }
#      - name: "lf_sky5"
#        config: { type: "line", width: 2, color: "yellow",
#                  start_position: [ 1053, 0 ], end_position: [ 1053, 1080 ] }
      - name: "left_ground"
        config: { type: "line", width: 2, color: "cyan",
                  start_position: [ 731, 0 ], end_position: [ 830, 193 ] }
      - name: "right_ground"
        config: { type: "line", width: 2, color: "cyan",
                  start_position: [ 1119, 333 ], end_position: [ 1291, 138 ] }
      - name: "left_up"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 615, 571 ], end_position: [ 756, 571 ] }
      - name: "left_down"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 597, 554 ], end_position: [ 597, 480 ] }
      - name: "right_up"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 1115, 576 ], end_position: [ 1269, 576 ] }
      - name: "right_down"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 1285, 555 ], end_position: [ 1285, 478 ] }
    flash:
