rm_referee:
  ui:
    trigger_change:
      - name: "step"
        config: { start_position: [ 400, 750 ], size: 15, width: 2, title: "step:  ", color: "white" }
      - name: "queue"
        config: { start_position: [ 400, 700 ], size: 15, width: 2, title: "queue: ", color: "yellow" }
      - name: "jog"
        config: { start_position: [ 1300, 750 ], size: 15, width: 2, title: "jog:  ", color: "white" }
      - name: "stone"
        config: { start_position: [ 1300, 700 ], size: 15, width: 2, title: "stone:", color: "yellow" }
      - name: "card"
        config: { start_position: [ 1300, 650 ], size: 15, width: 2, title: "card: ", color: "green" }
      - name: "sentry"
        config: { start_position: [ 1550, 750 ], size: 15, width: 2, title: "sentry:", color: "white" }
    fixed:
      - name: "stone_left"
        config: { type: "line", width: 2, color: "cyan",
                  start_position: [ 780, 401 ], end_position: [ 858, 571 ] }
      - name: "stone_right"
        config: { type: "line", width: 2, color: "cyan",
                  start_position: [ 1140, 386 ], end_position: [ 1124, 509 ] }
    time_change:
      - name: "effort"
        config: { start_position: [ 1500, 550 ], size: 15, width: 2, delay: 0.8 }
      - name: "temperature"
        config: { start_position: [ 1500, 500 ], size: 15, width: 2, delay: 0.8, title: "temp:   " }
      - name: "progress"
        config: { start_position: [ 400, 650 ], size: 15, width: 2, delay: 0.3, color: "green", title: "progress:" }
    flash:
      - name: "calibration"
        config: { start_position: [ 850, 700 ], size: 15, width: 2,
                  color: "yellow", content: "please calibrate!!", delay: 0.8 }
      - name: "card_warning"
        config: { start_position: [ 850, 750 ], size: 15, width: 2,
                  color: "green", content: "card stuck!!", delay: 0.8 }
