rm_hw:
  bus:
    - can0
  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  # Configurations of the actuators
  actuators:
    yaw_joint_motor:
      bus: can0
      id: 0x207
      type: rm_6020
      lp_cutoff_frequency: 30
    left_pitch_joint_motor:
      bus: can0
      id: 0x206
      type: rm_6020
      lp_cutoff_frequency: 30
    right_pitch_joint_motor:
      bus: can0
      id: 0x205
      type: rm_6020
      lp_cutoff_frequency: 30
    left_friction_wheel_joint_motor:
      bus: can0
      id: 0x201
      type: rm_3508
      lp_cutoff_frequency: 60
    right_friction_wheel_joint_motor:
      bus: can0
      id: 0x202
      type: rm_3508
      lp_cutoff_frequency: 60
    trigger_joint_motor:
      bus: can0
      id: 0x203
      type: rm_2006
      lp_cutoff_frequency: 150

