rm_hw:
  bus:
    - can0
    - can1
    - can2
    - can3
  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  # Configurations of the actuators
  actuators:
    upper_left_friction_wheel_joint_motor:
      bus: can1
      id: 0x201
      type: rm_3508
      lp_cutoff_frequency: 60
      lp_debug: true
    upper_right_friction_wheel_joint_motor:
      bus: can1
      id: 0x202
      type: rm_3508
      lp_cutoff_frequency: 60
      lp_debug: true
    upper_trigger_joint_motor:
      bus: can0
      id: 0x204
      type: rm_2006
      lp_cutoff_frequency: 100
      need_calibration: true
    drive_joint_motor:
      bus: can0
      id: 0x201
      type: rm_3508
      lp_cutoff_frequency: 100
    catapult_motor:
      bus: can0
      id: 0x202
      type: rm_2006
      lp_cutoff_frequency: 100
      need_calibration: true
    upper_pitch_joint_motor:
      bus: can1
      id: 0x205
      type: rm_3508
      lp_cutoff_frequency: 50
      need_calibration: true
    upper_yaw_joint_motor:
      bus: can1
      id: 0x206
      type: rm_6020
      lp_cutoff_frequency: 50
      need_calibration: true
    lower_left_friction_wheel_joint_motor:
      bus: can2
      id: 0x201
      type: rm_3508
      lp_cutoff_frequency: 60
      lp_debug: true
    lower_right_friction_wheel_joint_motor:
      bus: can2
      id: 0x202
      type: rm_3508
      lp_cutoff_frequency: 60
      lp_debug: true
    lower_trigger_joint_motor:
      bus: can0
      id: 0x203
      type: rm_2006
      lp_cutoff_frequency: 100
      need_calibration: true
    lower_pitch_joint_motor:
      bus: can2
      id: 0x205
      type: rm_3508
      lp_cutoff_frequency: 30
      need_calibration: true
    lower_yaw_joint_motor:
      bus: can2
      id: 0x206
      type: rm_6020
      lp_cutoff_frequency: 30
      need_calibration: true
  imus:
    upper_gimbal_imu:
      frame_id: upper_gimbal_imu
      bus: can1
      id: 0x100
      orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
      angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
      linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
      angular_vel_offset: [ -0.004, 0.006, -0.002 ]
      angular_vel_coeff: 0.0010652644
      accel_coeff: 0.0017944335
      temp_coeff: 0.125
      temp_offset: 23.0
      filter: complementary
      do_bias_estimation: false
      do_adaptive_gain: true
      gain_acc: 0.0003
    lower_gimbal_imu:
      frame_id: lower_gimbal_imu
      bus: can2
      id: 0x100
      orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
      angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
      linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
      angular_vel_offset: [ -0.004, 0.006, -0.002 ]
      angular_vel_coeff: 0.0010652644
      accel_coeff: 0.0017944335
      temp_coeff: 0.125
      temp_offset: 23.0
      filter: complementary
      do_bias_estimation: false
      do_adaptive_gain: true
      gain_acc: 0.0003
  tf_radars:
    left_tf_radar:
      bus: can3
      id: 0x211
    right_tf_radar:
      bus: can3
      id: 0x213
